### ISSUE TITLE
Not working after update HA to 2025.12.0b2

### ISSUE THREAD

**Issue by Largelos** [Lash-L/RoborockCustomMap#29]
Integration is not working after update to 2025.12.0b2, log contain error:
```
2025-11-28 00:36:26.882 ERROR (MainThread) [homeassistant.components.image] Error while setting up roborock_custom_map platform for image: 'RoborockDataUpdateCoordinator' object has no attribute 'maps'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 451, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/roborock_custom_map/image.py", line 26, in async_setup_entry
    async_add_entities(
    ~~~~~~~~~~~~~~~~~~^
        (
        ^
    ...<9 lines>...
        ),
        ^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 570, in _async_schedule_add_entities_for_entry
    new_entities if type(new_entities) is list else list(new_entities)
                                                    ~~~~^^^^^^^^^^^^^^
  File "/config/custom_components/roborock_custom_map/image.py", line 36, in <genexpr>
    for map_info in coord.maps.values()
                    ^^^^^^^^^^
AttributeError: 'RoborockDataUpdateCoordinator' object has no attribute 'maps'
```

**Comment by znanywawa** [comment]
Same for newest HA 2025.12.0

**Comment by guyke01** [comment]
The issue is also present in 2025.12.0 with the following error:

```
Logger: homeassistant.components.image
Bron: helpers/entity_platform.py:451
integratie: Afbeelding (documentatie, problemen)
Eerst voorgekomen: 20:15:59 (4 gebeurtenissen)
Laatst gelogd: 21:04:23

Error while setting up roborock_custom_map platform for image: 'RoborockDataUpdateCoordinator' object has no attribute 'maps'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 451, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/roborock_custom_map/image.py", line 26, in async_setup_entry
    async_add_entities(
    ~~~~~~~~~~~~~~~~~~^
        (
        ^
    ...<9 lines>...
        ),
        ^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 570, in _async_schedule_add_entities_for_entry
    new_entities if type(new_entities) is list else list(new_entities)
                                                    ~~~~^^^^^^^^^^^^^^
  File "/config/custom_components/roborock_custom_map/image.py", line 36, in <genexpr>
    for map_info in coord.maps.values()
                    ^^^^^^^^^^
AttributeError: 'RoborockDataUpdateCoordinator' object has no attribute 'maps'
```

**Comment by Lash-L** [comment]
should be fixed in version 0.1.2 of the component - give it a try! Thanks!
