### ISSUE TITLE
Multiple maps at HA 2025.12.0

### ISSUE THREAD

**Issue by znanywawa** [Lash-L/RoborockCustomMap#30]
I have installed newest version of HA 2025.12.0 and newest version of integration Roborock Custom Map Version 0.1.2.

There are two issues that I see:

1. I have separeted maps for full house and for balcony, so now, balcony map is not extracted, error from logs:
```
Logger: homeassistant.components.image
Source: helpers/entity_platform.py:676
integration: Image ([documentation](https://www.home-assistant.io/integrations/image), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+image%22))
First occurred: 22:56:49 (2 occurrences)
Last logged: 22:58:16

Error adding entity image.roborock_s7_balcony_custom for domain image with platform roborock_custom_map
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 676, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1002, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1380, in add_to_platform_finish
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1024, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1149, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1090, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/roborock_custom_map/image.py", line 111, in extra_state_attributes
    raise HomeAssistantError("Map flag not found in coordinator maps")
homeassistant.exceptions.HomeAssistantError: Map flag not found in coordinator maps
```

2. For mu full house map (which is default), i have following entry in logs:
```
Logger: homeassistant.components.image
Source: helpers/entity_platform.py:843
integration: Image ([documentation](https://www.home-assistant.io/integrations/image), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+image%22))
First occurred: 22:56:49 (2 occurrences)
Last logged: 22:58:16

Platform roborock_custom_map does not generate unique IDs. ID 4dolein5te4vrisu9cx3wr_custom_map_Full Home already exists - ignoring image.roborock_s7_full_home_custom
```

**Comment by Mikefila** [comment]
I can't get the custom maps to load at all. The core integration only loads the map active in the app. The other 2 maps show a timestamp but no image. 

I can switch the map in the app reload or restart HA, the active map shows an image. none of the custom load and onlty the active map has an image. This is what I see in my logs.

```
Logger: roborock.devices.mqtt_channel
Source: runner.py:289
First occurred: 6:08:04 PM (5 occurrences)
Last logged: 6:09:30 PM

Uncaught error in callback 'find_response': 'utf-8' codec can't decode byte 0x83 in position 16: invalid start byte
Uncaught error in callback 'find_response': 'utf-8' codec can't decode byte 0x92 in position 16: invalid start byte
Uncaught error in callback 'find_response': 'utf-8' codec can't decode byte 0xb1 in position 16: invalid start byte
Uncaught error in callback 'find_response': 'utf-8' codec can't decode byte 0xbb in position 16: invalid start byte
Uncaught error in callback 'find_response': 'utf-8' codec can't decode byte 0xd6 in position 16: invalid continuation byte
```

```
Logger: homeassistant.components.image
Source: helpers/entity_platform.py:451
integration: Image (documentation, issues)
First occurred: 6:05:30 PM (2 occurrences)
Last logged: 6:09:00 PM

Error while setting up roborock_custom_map platform for image: 'RoborockDataUpdateCoordinator' object has no attribute 'maps'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 451, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/roborock_custom_map/image.py", line 26, in async_setup_entry
    async_add_entities(
    ~~~~~~~~~~~~~~~~~~^
        (
        ^
    ...<9 lines>...
        ),
        ^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 570, in _async_schedule_add_entities_for_entry
    new_entities if type(new_entities) is list else list(new_entities)
                                                    ~~~~^^^^^^^^^^^^^^
  File "/config/custom_components/roborock_custom_map/image.py", line 36, in <genexpr>
    for map_info in coord.maps.values()
                    ^^^^^^^^^^
AttributeError: 'RoborockDataUpdateCoordinator' object has no attribute 'maps'
```

```
Logger: homeassistant.components.image
Source: helpers/entity_platform.py:843
integration: Image (documentation, issues)
First occurred: 6:05:20 PM (2 occurrences)
Last logged: 6:09:00 PM

Platform roborock does not generate unique IDs. ID 3ukcgbjuv5gnnf3kamm2fk_map_upstairs already exists - ignoring image.roborock_q7_max_upstairs
Platform roborock does not generate unique IDs. ID 3ukcgbjuv5gnnf3kamm2fk_map_3a already exists - ignoring image.roborock_q7_max_3a
```

**Comment by FerronN** [comment]
I've the same problem after updating my roborock S8 to 02.17.42 and also updating HA to 2025.12. The map of the core integration still works when I enable it.

**Comment by mateuszdrab** [comment]
Same issue here on a Roborock with a single map - this broke after `2025.12` installation overnight today

**Comment by xpucu** [comment]
Can confirm, I no longer have a map after updating to 2025.12

I reinstalled the custom maps integration to no avail. There is no map, no entities. 
I think it boils down to this error: `AttributeError: 'RoborockDataUpdateCoordinator' object has no attribute 'maps'`

Integration:

```
auto_update: false
display_precision: 0
installed_version: 0.1.1
in_progress: false
latest_version: 0.1.1
release_summary: null
release_url: https://github.com/Lash-L/RoborockCustomMap/releases/0.1.1
skipped_version: null
title: null
update_percentage: null
entity_picture: https://brands.home-assistant.io/_/roborock_custom_map/icon.png
friendly_name: Roborock Custom Map update
supported_features: 23
```

Log:

```
2025-12-05 10:57:14.843 INFO (MainThread) [roborock.devices.v1_channel] Successfully connected to local device 5C1HpkZLjtP1Mkl0P3TSN1
2025-12-05 10:57:19.082 INFO (MainThread) [homeassistant.components.image] Setting up roborock_custom_map.image
2025-12-05 10:57:19.083 ERROR (MainThread) [homeassistant.components.image] Error while setting up roborock_custom_map platform for image: 'RoborockDataUpdateCoordinator' object has no attribute 'maps'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 451, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/roborock_custom_map/image.py", line 26, in async_setup_entry
    async_add_entities(
    ~~~~~~~~~~~~~~~~~~^
        (
        ^
    ...<9 lines>...
        ),
        ^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 570, in _async_schedule_add_entities_for_entry
    new_entities if type(new_entities) is list else list(new_entities)
                                                    ~~~~^^^^^^^^^^^^^^
  File "/config/custom_components/roborock_custom_map/image.py", line 36, in <genexpr>
    for map_info in coord.maps.values()
                    ^^^^^^^^^^
AttributeError: 'RoborockDataUpdateCoordinator' object has no attribute 'maps'
2025-12-05 10:57:21.839 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 295, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 528, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 201, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 608, in _handle_coordinator_update
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1024, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1149, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1090, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sonarr/sensor.py", line 168, in extra_state_attributes
    return self.entity_description.attributes_fn(self.coordinator.data)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sonarr/sensor.py", line 70, in get_queue_attr
    f"S{item.episode.seasonNumber:02d}E{item.episode.episodeNumber:02d}"
        ^^^^^^^^^^^^^^^^^^^^^^^^^
```


Found something curios in the logs:

```
2025-12-05 09:34:41.468 INFO (MainThread) [homeassistant.components.button] Setting up roborock.button
2025-12-05 09:34:41.470 INFO (MainThread) [homeassistant.components.image] Setting up roborock.image
2025-12-05 09:34:41.471 ERROR (MainThread) [homeassistant.components.image] Platform roborock does not generate unique IDs. ID 5c1hpkzljtp1mkl0p3tsn1_map_Home already exists - ignoring image.roborock_qrevo_s5v_home
2025-12-05 09:34:41.471 INFO (MainThread) [homeassistant.components.number] Setting up roborock.number
```

Vacuum is Roborock Qrevo S5V Robot Vacuum. 


HA:
```
<slot name="heading"><h2 id="title" class="mdc-dialog__title"><div class="header_title"><span>System information</span> </div> </h2></slot> <div id="content" class="mdc-dialog__content"> <slot id="contentSlot"> <div>    <div> 
Version | core-2025.12.0
-- | --
Installation type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
Container architecture | aarch64
User | root
Virtual environment | false
Python version | 3.13.9
Operating system family | Linux
Operating system version | 6.12.47-haos-raspi
CPU architecture | aarch64
Timezone | America/Phoenix
Configuration directory | /config

</div></div></slot></div>
```

**Comment by Dulcow** [comment]
I confirm that the last update fixed the issue ;-) Thank you very much!

D.
